### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by theDVL** [bitfocus/companion-module-generic-tcp-serial#7] opened 2022-08-30 07:05 UTC
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No serial ports found. 
This worked in previous versions. 

### Environment (please complete the following information)

```markdown
- OS:Windows 10
- Browser:Chrome
- Companion Version:230
```

**Comment by Xcodo** [comment] 2022-08-30 13:09
Duplicate of #5.

The module is fixed already with #6, it will work again in the next release.

**Comment by theDVL** [comment] 2022-08-30 13:11
Thank you for the fast reply! 

I have a gig next week..... will the release come soon?

**Comment by Xcodo** [comment] 2022-08-30 13:15
No idea when the next stable build will be out I'm afraid (@josephdadams might be able to comment), but the beta builds include the fix already - https://bitfocus.io/companion/download/builds/

**Comment by josephdadams** [comment] 2022-08-30 13:16
Yes use a Beta build if you want it to work

**Closed as completed by josephdadams** 2022-08-30 13:16 UTC
Labels: bug

**Comment by theDVL** [comment] 2022-08-30 13:48
You guys are the BEST! Thank you again
